apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruitmng
  labels:
    app: recruitmng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recruitmng
  template:
    metadata:
      labels:
        app: recruitmng
    spec:
      containers:
        - name: recruitmng
          image: "username/recruitmng:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
