server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: recruitmng
          uri: http://localhost:8082
          predicates:
            - Path=/recruits/**, 
        - id: hr
          uri: http://localhost:8083
          predicates:
            - Path=/hrs/**, 
        - id: department
          uri: http://localhost:8084
          predicates:
            - Path=/departments/**, 
        - id: mypage
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: recruitmng
          uri: http://recruitmng:8080
          predicates:
            - Path=/recruits/**, 
        - id: hr
          uri: http://hr:8080
          predicates:
            - Path=/hrs/**, 
        - id: department
          uri: http://department:8080
          predicates:
            - Path=/departments/**, 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
