---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruitmng
  labels:
    app: recruitmng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recruitmng
  template:
    metadata:
      labels:
        app: recruitmng
    spec:
      imagePullSecrets:
        - name: acr-secret  # ACR 접근을 위한 Secret 이름
      containers:
        - name: recruitmng
          image: user02.azurecr.io/recruitmng:latest
          ports:
            - containerPort: 8080
          # readinessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 10
          # livenessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 120
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr
  labels:
    app: hr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr
  template:
    metadata:
      labels:
        app: hr
    spec:
      imagePullSecrets:
        - name: acr-secret  # ACR 접근을 위한 Secret 이름
      containers:
        - name: hr
          image: user02.azurecr.io/hr:latest
          ports:
            - containerPort: 8080
          # readinessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 10
          # livenessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 120
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: department
  labels:
    app: department
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department
  template:
    metadata:
      labels:
        app: department
    spec:
      imagePullSecrets:
        - name: acr-secret  # ACR 접근을 위한 Secret 이름
      containers:
        - name: department
          image: user02.azurecr.io/department:latest
          ports:
            - containerPort: 8080
          # readinessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 10
          # livenessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 120
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypage
  labels:
    app: mypage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypage
  template:
    metadata:
      labels:
        app: mypage
    spec:
      imagePullSecrets:
        - name: acr-secret  # ACR 접근을 위한 Secret 이름
      containers:
        - name: mypage
          image: user02.azurecr.io/mypage:latest
          ports:
            - containerPort: 8080
          # readinessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 10
          # livenessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 120
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: recruitmng
  labels:
    app: recruitmng
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: recruitmng


---


apiVersion: v1
kind: Service
metadata:
  name: hr
  labels:
    app: hr
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hr


---


apiVersion: v1
kind: Service
metadata:
  name: department
  labels:
    app: department
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: department


---


apiVersion: v1
kind: Service
metadata:
  name: mypage
  labels:
    app: mypage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mypage

