name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: user02.azurecr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./recruitmng/pom.xml
          mvn clean package -f ./hr/pom.xml
          mvn clean package -f ./department/pom.xml
          mvn clean package -f ./mypage/pom.xml

      - name: Docker Build and push for Recruitmng
        uses: docker/build-push-action@v4
        with:
          context: ./recruitmng
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            user02.azurecr.io/${{ github.repository }}/recruitmng:latest
            user02.azurecr.io/${{ github.repository }}/recruitmng:${{ github.ref_name }}
            
      - name: Docker Build and push for Hr
        uses: docker/build-push-action@v4
        with:
          context: ./hr
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            user02.azurecr.io/${{ github.repository }}/hr:latest
            user02.azurecr.io/${{ github.repository }}/hr:${{ github.ref_name }}
            
      - name: Docker Build and push for Department
        uses: docker/build-push-action@v4
        with:
          context: ./department
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            user02.azurecr.io/${{ github.repository }}/department:latest
            user02.azurecr.io/${{ github.repository }}/department:${{ github.ref_name }}
            
      - name: Docker Build and push for Mypage
        uses: docker/build-push-action@v4
        with:
          context: ./mypage
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            user02.azurecr.io/${{ github.repository }}/mypage:latest
            user02.azurecr.io/${{ github.repository }}/mypage:${{ github.ref_name }}
